"use client";

import { useMemo, useState } from "react";
const items=[
 {id:1,title:"KYC article and verification flow",project:"KYC Campaign",status:"In progress",priority:"High",due:"Today"},
 {id:2,title:"Crypto Digest carousel",project:"Content",status:"Review",priority:"Medium",due:"Aug 30"},
 {id:3,title:"Rakhi YouTube thumbnail",project:"Rakhi Campaign",status:"Completed",priority:"Low",due:"Aug 28"},
 {id:4,title:"Landing page copy review",project:"Website",status:"Not started",priority:"High",due:"Sep 01"},
 {id:5,title:"Weekly campaign performance",project:"Marketing",status:"In progress",priority:"Medium",due:"Sep 02"},
];
export default function MyWork(){const [filter,setFilter]=useState("All");const [q,setQ]=useState("");const filtered=useMemo(()=>items.filter(x=>(filter==="All"||x.status===filter)&&x.title.toLowerCase().includes(q.toLowerCase())),[filter,q]);return <div className="shell"><aside className="sidebar"><div className="brand">WORK OS</div><div className="workspace"><small>WORKSPACE</small><strong>Acme Workspace⌄</strong></div><div className="nav-label">WORKSPACE</div><nav className="nav"><a href="/">Home</a><a className="active" href="/my-work">My Work</a><a href="/projects">Projects</a><a href="#">Reports</a><a href="#">Team</a></nav><div className="nav-label" style={{marginTop:18}}>MANAGE</div><nav className="nav"><a href="#">Inbox</a><a href="/calendar">Calendar</a><a href="#">Settings</a></nav></aside><main className="main"><header className="topbar"><div className="crumb">Workspace / My Work</div><div className="top-actions"><div className="avatar">RK</div></div></header><section className="content"><div className="headline"><div><div className="eyebrow">YOUR WORK</div><h1>My Work</h1><p>Everything assigned to you, in one place.</p></div><a className="primary" href="/projects">+ New task</a></div><div className="tabs">{["All","Not started","In progress","Review","Completed"].map(x=><button className={filter===x?"selected":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter tasks..."/></div><section className="panel"><div className="panel-head"><strong>{filter} tasks</strong><span className="muted">{filtered.length} shown</span></div>{filtered.map(t=><div className="task" key={t.id}><div className="check"/><div><div className="task-title">{t.title}</div><div className="project">{t.project}</div></div><div className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</div><div><span className={`pill ${t.status==='In progress'?'progress':t.status==='Review'?'review':t.status==='Completed'?'done':''}`}>{t.status}</span></div><div className="muted">{t.due}</div></div>)}{filtered.length===0&&<div className="empty">No tasks match this filter.</div>}</section></section></main><style jsx>{`.tabs{display:flex;align-items:center;gap:3px;margin-bottom:12px;border-bottom:1px solid #e4e6ea}.tabs button{border:0;background:transparent;padding:9px 11px;color:#777d86;font-size:11px}.tabs button.selected{color:#17191d;font-weight:700;border-bottom:2px solid #24272d}.tabs input{margin-left:auto;border:1px solid #e0e3e8;border-radius:7px;padding:7px 9px;font-size:11px;margin-bottom:5px}.empty{text-align:center;padding:50px;color:#888;font-size:12px}@media(max-width:700px){.tabs{overflow:auto}.tabs input{display:none}}`}</style></div>}
