"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "../../lib/supabase-browser";

export default function Onboarding(){
 const router=useRouter(); const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{const s=supabaseBrowser();if(!s){router.replace("/auth");return;}s.auth.getSession().then(({data})=>{if(!data.session)router.replace("/auth")});},[router]);
 const updateName=(v:string)=>{setName(v);setSlug(v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,40))};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");const s=supabaseBrowser();if(!s){setError("Supabase is not configured.");setBusy(false);return;}const {data,error}=await s.rpc("create_workspace",{workspace_name:name,workspace_slug:slug});if(error){setError(error.message);setBusy(false);return;}if(data)router.replace("/");};
 return <main className="page"><div className="card"><div className="brand">WORK OS</div><div className="step">STEP 1 OF 1</div><h1>Create your workspace</h1><p>Your workspace is where your team, projects and tasks live.</p><form onSubmit={submit}><label>Workspace name<input required minLength={2} value={name} onChange={e=>updateName(e.target.value)} placeholder="Acme Inc."/></label><label>Workspace URL <span>/ {slug||"your-workspace"}</span><input required minLength={2} pattern="[a-z0-9-]+" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))}/></label>{error&&<div className="error">{error}</div>}<button disabled={busy} type="submit">{busy?"Creating workspace…":"Create workspace"}</button></form></div><style jsx>{`.page{min-height:100vh;display:grid;place-items:center;background:#f7f8fa;padding:20px}.card{width:440px;background:#fff;border:1px solid #e3e5e9;border-radius:12px;padding:34px}.brand{font-weight:800;font-size:15px;letter-spacing:.04em;margin-bottom:35px}.step{font-size:9px;font-weight:800;letter-spacing:.08em;color:#969ba3;margin-bottom:9px}.card h1{font-size:25px;letter-spacing:-.04em;margin:0 0 7px}.card p{font-size:12px;color:#7b818a;line-height:1.5;margin:0 0 27px}.card label{display:block;font-size:11px;font-weight:700;margin-bottom:15px}.card label span{font-weight:400;color:#999}.card input{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:11px;border:1px solid #dfe2e7;border-radius:7px;font-size:12px;outline:none}.card button{width:100%;margin-top:7px;padding:11px;border:0;border-radius:7px;background:#24272d;color:#fff;font-weight:700;font-size:11px}.card button:disabled{opacity:.55}.error{font-size:11px;color:#a33b3b;background:#fff3f3;border:1px solid #f0d5d5;padding:9px;border-radius:6px;margin-bottom:10px}`}</style></main>}
