"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "../../lib/supabase-browser";

export default function Auth(){
 const router=useRouter(); const [mode,setMode]=useState<"signin"|"signup">("signin"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{const s=supabaseBrowser(); if(!s)return; s.auth.getSession().then(({data})=>{if(data.session)router.replace("/")});},[router]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setMessage("");setBusy(true);const s=supabaseBrowser();if(!s){setMessage("Supabase is not configured. Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in Vercel.");setBusy(false);return;}const result=mode==="signin"?await s.auth.signInWithPassword({email,password}):await s.auth.signUp({email,password});if(result.error)setMessage(result.error.message);else if(mode==="signup"&&!result.data.session)setMessage("Account created. Check your email to confirm your account.");else router.replace("/");setBusy(false)};
 return <main className="auth"><div className="auth-card"><div className="brand">WORK OS</div><h1>{mode==="signin"?"Welcome back":"Create your workspace account"}</h1><p>{mode==="signin"?"Sign in to continue to your workspace.":"Start organizing your team's work."}</p><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Password<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><button className="primary" disabled={busy} type="submit">{busy?"Please wait…":mode==="signin"?"Sign in":"Create account"}</button></form>{message&&<div className="notice">{message}</div>}<button className="switch" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setMessage("")}}>{mode==="signin"?"Need an account? Create one":"Already have an account? Sign in"}</button></div><style jsx>{`.auth{min-height:100vh;display:grid;place-items:center;background:#f7f8fa;padding:20px}.auth-card{width:390px;background:#fff;border:1px solid #e4e6ea;border-radius:12px;padding:30px}.brand{font-size:16px;font-weight:800;letter-spacing:.04em;margin-bottom:36px}.auth h1{font-size:23px;letter-spacing:-.03em;margin:0 0 7px}.auth p{font-size:12px;color:#7d828c;margin:0 0 26px}.auth label{display:block;font-size:11px;font-weight:650;margin-bottom:14px}.auth input{display:block;width:100%;margin-top:6px;border:1px solid #dfe2e7;border-radius:7px;padding:10px;outline:none;font-size:12px}.auth .primary{width:100%;margin-top:7px}.auth .primary:disabled{opacity:.6;cursor:wait}.notice{background:#f4f6f8;border:1px solid #e2e5e9;border-radius:7px;padding:10px;font-size:11px;color:#666d77;margin-top:14px;line-height:1.5}.switch{border:0;background:none;width:100%;padding:15px 0 0;color:#555b65;font-size:11px}`}</style></main>
}