"use client";
import {useEffect,useState} from "react";
import {supabaseBrowser} from "../lib/supabase-browser";

type Task={id:string;title:string;status:string;priority:string;description:string|null;due_date:string|null;position:number;assignee_id?:string|null};
type Member={id:string;name:string};
const statuses=["not_started","in_progress","review","completed","blocked"];const priorities=["low","medium","high","urgent"];
export default function TaskDetails({task,onClose,onSaved}:{task:Task;onClose:()=>void;onSaved:(task:Task)=>void}){const [title,setTitle]=useState(task.title);const [description,setDescription]=useState(task.description??"");const [status,setStatus]=useState(task.status);const [priority,setPriority]=useState(task.priority);const [due,setDue]=useState(task.due_date??"");const [assignee,setAssignee]=useState(task.assignee_id??"");const [members,setMembers]=useState<Member[]>([]);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
useEffect(()=>{setTitle(task.title);setDescription(task.description??"");setStatus(task.status);setPriority(task.priority);setDue(task.due_date??"");setAssignee(task.assignee_id??"")},[task.id]);
useEffect(()=>{const load=async()=>{const c=supabaseBrowser();if(!c)return;const {data:{user}}=await c.auth.getUser();if(!user)return;const {data:ws}=await c.from("workspace_members").select("workspace_id").eq("user_id",user.id).limit(1).maybeSingle();if(!ws)return;const {data:ms}=await c.from("workspace_members").select("user_id").eq("workspace_id",ws.workspace_id);const ids=(ms??[]).map(x=>x.user_id);if(!ids.length)return;const {data:profiles}=await c.from("profiles").select("id,full_name,email").in("id",ids);setMembers((profiles??[]).map(x=>({id:x.id,name:x.full_name||x.email||"Member"})))};load()},[]);
const save=async()=>{const c=supabaseBrowser();if(!c||!title.trim())return;setSaving(true);setError("");const patch={title:title.trim(),description:description.trim()||null,status,priority,due_date:due||null,assignee_id:assignee||null,updated_at:new Date().toISOString()};const {data,error}=await c.from("tasks").update(patch).eq("id",task.id).select("id,title,status,priority,description,due_date,position,assignee_id").single();if(error)setError(error.message);else{onSaved(data as Task)}setSaving(false)};
return <div className="drawer"><div className="top"><span>Task details</span><button onClick={onClose}>×</button></div><input className="title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Task title"/><label>Status</label><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><option key={x} value={x}>{x.replace("_"," ")}</option>)}</select><label>Priority</label><select value={priority} onChange={e=>setPriority(e.target.value)}>{priorities.map(x=><option key={x} value={x}>{x}</option>)}</select><label>Assignee</label><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><label>Due date</label><input type="date" value={due} onChange={e=>setDue(e.target.value)}/><label>Description</label><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add task details..."/>{error&&<div className="error">{error}</div>}<div className="actions"><button disabled={saving} onClick={onClose}>Cancel</button><button className="primary" disabled={saving||!title.trim()} onClick={save}>{saving?"Saving…":"Save changes"}</button></div><style jsx>{`.drawer{position:fixed;right:0;top:0;bottom:0;width:390px;background:#fff;border-left:1px solid #ddd;box-shadow:-10px 0 35px rgba(0,0,0,.08);z-index:30;padding:20px 22px;overflow:auto}.top{display:flex;justify-content:space-between;color:#858a93;font-size:11px}.top button{border:0;background:none;font-size:22px}.title{font-size:20px;font-weight:700;border:0;outline:none;width:100%;margin:28px 0 22px;padding:0}.drawer label{display:block;font-size:10px;color:#777d86;font-weight:700;margin:15px 0 6px}.drawer select,.drawer input:not(.title),.drawer textarea{width:100%;box-sizing:border-box;border:1px solid #e0e2e6;border-radius:6px;background:#fff;padding:9px;font-size:11px}.drawer textarea{height:120px;resize:vertical}.error{margin-top:12px;background:#fff0f0;border:1px solid #f0d3d3;color:#a34747;padding:9px;border-radius:6px;font-size:10px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}.actions button:not(.primary){border:1px solid #ddd;background:#fff;border-radius:7px;padding:9px 13px;font-size:11px}`}</style></div>}
