"use client";

import { FormEvent, useState } from "react";
import { supabaseBrowser } from "../../lib/supabase-browser";

export default function Login() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [mode,setMode]=useState<"signin"|"signup">("signin"); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");const supabase=supabaseBrowser();if(!supabase){setMessage("Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in Vercel.");setLoading(false);return;}const result=mode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error)setMessage(result.error.message);else setMessage(mode==="signin"?"Signed in successfully. You can return to the workspace.":"Account created. Check your email if confirmation is enabled.");setLoading(false);}
  return <main className="auth"><section className="auth-card"><div className="logo">WORK OS</div><h1>{mode==="signin"?"Welcome back":"Create your workspace account"}</h1><p>{mode==="signin"?"Sign in to continue to your workspace.":"Start building your team's work system."}</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} autoComplete={mode==="signin"?"current-password":"new-password"}/></label><button disabled={loading}>{loading?"Working…":mode==="signin"?"Sign in":"Create account"}</button></form>{message&&<div className="message">{message}</div>}<button className="switch" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setMessage("")}}>{mode==="signin"?"Need an account? Create one":"Already have an account? Sign in"}</button></section><style jsx>{`.auth{min-height:100vh;display:grid;place-items:center;background:#f7f8fa;padding:20px}.auth-card{width:390px;background:#fff;border:1px solid #e2e4e8;border-radius:12px;padding:32px;box-shadow:0 15px 45px rgba(20,22,25,.06)}.logo{font-size:13px;font-weight:800;letter-spacing:.08em;margin-bottom:38px}.auth h1{font-size:24px;letter-spacing:-.03em;margin:0 0 7px}.auth p{font-size:12px;color:#7d828c;margin:0 0 25px}.auth label{display:block;font-size:11px;font-weight:650;margin-bottom:14px}.auth input{display:block;width:100%;margin-top:6px;border:1px solid #dfe2e7;border-radius:7px;padding:10px;outline:none}.auth form button{width:100%;border:0;border-radius:7px;padding:11px;background:#24272d;color:#fff;font-size:12px;font-weight:700;margin-top:5px}.auth form button:disabled{opacity:.6}.message{font-size:11px;color:#666d76;background:#f5f6f8;border-radius:7px;padding:10px;margin-top:13px}.switch{width:100%;border:0;background:transparent;padding:13px 0 0;font-size:11px;color:#666d76}`}</style></main>;
}
