"use client";
import {useEffect,useState} from "react";
import {supabaseBrowser} from "../../lib/supabase-browser";
import {getUserWorkspace,type Workspace} from "../../lib/workspace";
type N={id:string;title:string;body:string|null;read_at:string|null;created_at:string};
export default function Inbox(){const[n,setN]=useState<N[]>([]);const[w,setW]=useState<Workspace|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
useEffect(()=>{(async()=>{const c=supabaseBrowser();if(!c){setError("Supabase is not configured.");setLoading(false);return}const{data:{user}}=await c.auth.getUser();if(!user){setError("Please sign in again.");setLoading(false);return}try{const ws=await getUserWorkspace(c,user.id);setW(ws);if(!ws){setError("No workspace found.");return}const{data,error:e}=await c.from("notifications").select("id,title,body,read_at,created_at").eq("user_id",user.id).order("created_at",{ascending:false});if(e)throw e;setN((data??[]) as N[])}catch(e){setError(e instanceof Error?e.message:"Could not load notifications")}finally{setLoading(false)}})()},[]);
const mark=async(id:string)=>{const c=supabaseBrowser();if(!c)return;const now=new Date().toISOString();setN(x=>x.map(v=>v.id===id?{...v,read_at:now}:v));const{error:e}=await c.from("notifications").update({read_at:now}).eq("id",id);if(e)setError(e.message)};
return <div className="shell"><aside className="sidebar"><div className="brand">WORK OS</div><div className="workspace"><small>WORKSPACE</small><strong>{w?.name??"Workspace"}⌄</strong></div><div className="nav-label">WORKSPACE</div><nav className="nav"><a href="/">Home</a><a href="/my-work">My Work</a><a href="/projects">Projects</a><a href="/team">Team</a></nav><div className="nav-label">MANAGE</div><nav className="nav"><a className="active" href="/inbox">Inbox</a><a href="/calendar">Calendar</a><a href="#">Settings</a></nav></aside><main className="main"><header className="topbar"><div className="crumb">Workspace / Inbox</div></header><section className="content"><div className="headline"><div><div className="eyebrow">NOTIFICATIONS</div><h1>Inbox</h1><p>Updates and notifications for your work.</p></div></div>{error&&<div className="error">{error}</div>}<section className="panel"><div className="panel-head"><strong>Notifications</strong><span className="muted">{loading?"Loading…":`${n.filter(x=>!x.read_at).length} unread`}</span></div>{n.map(x=><button className={`notice ${x.read_at?"read":""}`} key={x.id} onClick={()=>mark(x.id)}><div><strong>{x.title}</strong><p>{x.body}</p></div><small>{new Date(x.created_at).toLocaleString()}</small></button>)}{!loading&&!n.length&&<div className="empty">You're all caught up.</div>}</section></section></main><style jsx>{`.notice{width:100%;display:flex;text-align:left;justify-content:space-between;gap:15px;padding:15px 16px;border:0;border-bottom:1px solid #f0f1f3;background:#fff}.notice:not(.read){background:#fafbfc}.notice strong{font-size:12px}.notice p{margin:5px 0 0;color:#777;font-size:11px}.notice small{color:#999;font-size:9px;white-space:nowrap}.error{background:#fff0f0;border:1px solid #f0d3d3;color:#a34747;padding:10px;border-radius:7px;font-size:11px;margin-bottom:12px}.empty{text-align:center;padding:50px;color:#888;font-size:12px}`}</style></div>}
